modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="more_ores_and_resources"
version="1.0.0"
displayName="More Ores and Resources!"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Alexander"
authors="Alexander/ItsAlexander91"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.more_ores_and_resources]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.12,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.more_ores_and_resources]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration